---
                - name: Install PHP packages
                  apt:
                                pkg:
                                        - php
                                        - libapache2-mod-php
                                        - php-mysql 
                                        - php-curl
                                        - php-gd 
                                        - php-xml
                                        - php-mbstring
                                        - php-xmlrpc
                                        - php-zip
                                        - php-soap
                                        - php-intl 
